variant: fix unused args warnings
Some of them are clang-specific (might even require /permissive-), other - msvc.

Example of warning
variant.h(133,24): error: unused parameter 'pThis' [-Werror,-Wunused-parameter]